// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://paujoavgtagujbzfhrwi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBhdWpvYXZndGFndWpiemZocndpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5MjEwOTIsImV4cCI6MjA3MzQ5NzA5Mn0.Yn9Mvah3Do0Cp18Sj2nidmLmi_BO3wTc7_RgaYvMJR4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});